### PR TITLE
Update exporter to use an earth engine dataset instead of a fusion table

### LINKED ISSUE #3: Fusion tables are now deprecated
Can you suggest me an alternate, now that the fusion tables are not avaiable, and also the necessary changes ?

### PR DESCRIPTION
**Pull request by gabrieltseng**
Closes #3

### CODE REVIEW

**Comment by kushagra-2503** [comment]
You can merge the code, it works fine. Thanks for your help.

**Review by SaiDeepthiYeddula — COMMENTED** [review]
In the updated file, before line 160, don't we need to filter the region with state_id too?

**Comment by kushagra-2503** [comment]
A CountyFP uniquely determines a county

**Comment by SaiDeepthiYeddula** [comment]
Thanks for your response. I got a problem in exporting with county "185", the image files got generated with inappropriate file names. 
For example, for state 17 and county 185, 8 image files with names ("17_185-0000000000-0000000000.tif", "17_185-0000000000-0000000768.tif", "17_185-0000000000-0000001536.tif",...so on) got generated with different file sizes.
Do you have any idea about this?

**Comment by gabrieltseng** [comment]
@SaiDeepthiYeddula yes it turns out you were right. Sorry for this mistake; it's fixed in this commit: https://github.com/gabrieltseng/pycrop-yield-prediction/commit/ac25e09670c4f904ba4d20c94e311e0162d7b165

**Pull request merged**
